apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-share
  labels:
    app: treetracker-share
spec:
  replicas: 2
  selector:
    matchLabels:
      app: treetracker-share
  template:
    metadata:
      labels:
        app: treetracker-share
    spec:
      containers:
      - name: treetracker-share
        image: greenstand/treetracker-share:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
          - name: NODE_LOG_LEVEL
            value: trace
          - name: REMOTE_LOG_URL
            value: http://104.131.78.177:8000
